services:
  web:
    build: ./packages/web
    ports:
      - 80:80
    depends_on:
      - database
    environment:
      - API_URL=http://api:8080
  api:
    build: ./packages/api
    ports:
      - 4000:8080
    depends_on:
      - database
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=http://database
      - PGPORT=5432
      - PGDATABASE=${POSTGRES_DB}
  database:
    image: postgres:14
    restart: always
    ports:
      - 5001:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata_afl:/var/lib/postgresql/data

